name: Generate TON DNS Config
on: workflow_dispatch
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Files
        run: |
          DOMAIN="telefilm-tg.ton"
          if [ -z "$DOMAIN" ]; then
            DOMAIN="telefilm-tg.ton"
          fi
          
          ADNL=$(openssl rand -hex 32)
          
          echo '<!DOCTYPE html>' > index.html
          echo '<html>' >> index.html
          echo '<head>' >> index.html
          echo '  <title>Hello World</title>' >> index.html
          echo '</head>' >> index.html
          echo '<body>' >> index.html
          echo '  <h1>Hello World</h1>' >> index.html
          echo '</body>' >> index.html
          echo '</html>' >> index.html
          
          echo '<dns-config>' > dns-config.xml
          echo "  <domain>$DOMAIN</domain>" >> dns-config.xml
          echo "  <adnl>$ADNL</adnl>" >> dns-config.xml
          echo '</dns-config>' >> dns-config.xml

      - name: Commit Files to Repository
        run: |
          git config --global user.email "${{ vars.EMAIL }}"
          git config --global user.name "HiPlatform Actions CI/CD"
          git add dns-config.xml index.html
          git commit -m "Add generated files for TON DNS"
          git push
