name: Build TON DNS Website

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate dns-config.xml
        run: |
          cat << 'EOF' > dns-config.xml
          <?xml version="1.0" encoding="UTF-8"?>
          <dns-config>
            <domain>telefilm-tg.ton</domain>
            <adnl>ADNL</adnl>
          </dns-config>
          EOF

      - name: Generate index.html
        run: |
          cat << 'EOF' > index.html
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <title>Hello World</title>
          </head>
          <body>
            <h1>Hello World</h1>
          </body>
          </html>
          EOF

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: website-files
          path: |
            dns-config.xml
            index.html
